### ISSUE TITLE
Implement configuration file support

### ISSUE THREAD

**Issue by ebastos** [ebastos/shell-history#12]
Scenario:

User should be able to enable/disable the shell-history via configuration file.
File should be a json located under ~/.config/shell-history.json

* If file exists, reads the file and checks for "enabled" flag. (boolean)
* If file does not exist or "enabled" flag does not exist, should default to True.

**Comment by cbolgiano** [comment]
Created a PR for this issue: https://github.com/ebastos/shell-history/pull/13
