### ISSUE TITLE
Enhance history HTML page

### ISSUE THREAD

**Issue by ebastos** [ebastos/shell-history#8]
The HTML page presenting the shell history is very [basic and ugly](https://cloudflare-ipfs.com/ipfs/QmVWmPHHiz4pNaBQ5pZAkqmcxcKjDAtcD7k2XC7SouGfW7).

I would appreciate any help making it better.

**Comment by edikxl** [comment]
As I see, html file doesn't have data for test. How do I create condititions to see page as at your screenshot?

**Comment by ebastos** [comment]
Hi, @edikxl 

I guess having everything deployed is really painful at this point, so I just exported a few samples into a [csv file here](https://gist.github.com/ebastos/9c382fd8096756ab744796e430284954).

Let me know if that helps.

Thanks!

**Comment by edikxl** [comment]
Sorry, @ebastos.

I am not a professional at backend. I can make a clean html with your test data from csv, push it, and you will write code that pastes data that you need.

Is that comfortable for you?

**Comment by edikxl** [comment]
@ebastos, no. But if I have a time today I will spend it for learning.
