### ISSUE TITLE
Support redacting commands

### ISSUE THREAD

**Issue by ebastos** [ebastos/shell-history#9]
Scenario:

User does not want sensitive information like passwords and secret keys to be logged.
Individual users may have different requirements for what needs to be redacted prior to uploading to the server.

Idea:

There should be support for a local configuration file supporting patterns of strings to be filtered out.
Maybe a regex-based key-value pair like:

`REDACT_FILTER = {'--password=.* ': '--password=REDACTED '}`

**Comment by Jitsusama** [comment]
I'm starting to take a look at this now. First step, figure out how to get a build environment going :(

Getting a weird error about your history package. Looks to be protobuf related. Trying to get protobuf-c installed on MacOS and then will try out your Makefile instructions on building, 'cause it looks like auto-generated code stuff. You might want to add that to your dev docs.

**Comment by Jitsusama** [comment]
I got the build environment going. Installing protobuf-c and then running the protoc command did it.

**Comment by Jitsusama** [comment]
Me thinks this ticket can probably be resolved now.
